# Generated by Django 3.1.6 on 2021-02-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
