# Generated by Django 3.1.6 on 2021-02-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210219_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='writer',
        ),
    ]
