# Generated by Django 3.1.6 on 2021-02-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210219_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_writer', to='users.UserProfile'),
        ),
    ]
